main/urls.py
from django.conf.urls import url
from . import views
# SET THE NAMESPACE!
app_name = 'main'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),

]

website/urls.py
from django.urls import path
from django.contrib import admin
from django.conf.urls import url,include
from main import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^special/', views.special, name='special'),
    url(r'^main/', include('main.urls')),
    url(r'^success/$', views.successpage, name='successpage'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^success/mainpage/$', views.mainpage, name='mainpage'),



]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class movies(models.Model):
    movie_title= models.CharField(max_length=200)
    genre= models.CharField(max_length=200)

    def __str__(self):
        return str(self.id) + '-'+ self.movie_title

class ratings(models.Model):
    movie_id= models.ForeignKey(movies,on_delete= models.CASCADE)
    user_id= models.IntegerField
    rating= models.IntegerField

    def __str__(self):
        return str(self.movie_id) + '-'+'-'+self.user_id + '-'+ self.rating

main/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

main/views.py
from django.shortcuts import render, redirect
from main.forms import UserForm
from main.models import movies
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'main/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
    return render(request, 'main/registeration.html',
                  {'user_form': user_form,
                   'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                data = request.POST.get('textbox1')

                context = {'data': data}
                return redirect('/success')
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'main/login.html', {})


def successpage(request):
    return render(request, 'main/successpage.html', context={})


def mainpage5(request):
    data = request.POST.get('search')
    def recommender(request):
        import pandas as pd
        # import matplotlib.pyplot as plt
        import seaborn as sns
        sns.set_style('white')
        # %matplotlib inline
        df_movies = pd.read_csv(r"C:\Users\Welcome\Desktop\Project\movielens data sets\movies.csv")
        df_ratings = pd.read_csv(r"C:\Users\Welcome\Desktop\Project\movielens data sets\ratings.csv")
        df = pd.merge(df_movies, df_ratings, on='movieId', how='outer')
        (df.groupby('title')['rating'].count().sort_values(ascending=False).head())
        ratings = pd.DataFrame(df.groupby('title')['rating'].mean())
        moviemat = df.pivot_table(index='userId', columns='title', values='rating')
        ratings = pd.DataFrame(df.groupby('title')['rating'].mean())
        ratings['num of ratings'] = pd.DataFrame(df.groupby('title')['rating'].count())
        # print(ratings.sort_values('num of ratings',ascending=False).head(10))
        movie_name = request.POST.get('search')
        user_ratings1 = moviemat[movie_name]
        user_ratings1.head()
        similar_to_starwars = moviemat.corrwith(user_ratings1)
        corr_ur = pd.DataFrame(similar_to_starwars, columns=['Correlation'])
        corr_ur.dropna(inplace=True)
        corr_ur.sort_values('Correlation', ascending=False).head(10)
        corr_ur = corr_ur.join(ratings['num of ratings'])
        variable= corr_ur[corr_ur['num of ratings'] > 100].sort_values('Correlation', ascending=False).head()
        variable.dropna(inplace=True)
        variable_dict = variable.to_dict('series')
        return variable_dict

    context= recommender(request)
    print(context)
    return render(request, 'main/mainpage.html', context)


def mainpage(request):

    data = request.POST.get('search')
    import pandas as pd
    # import matplotlib.pyplot as plt
    import seaborn as sns
    sns.set_style('white')
    # %matplotlib inline
    df_movies = pd.read_csv(r"C:\Users\Welcome\Desktop\Project\movielens data sets\movies.csv")
    df_ratings = pd.read_csv(r"C:\Users\Welcome\Desktop\Project\movielens data sets\ratings.csv")
    df = pd.merge(df_movies, df_ratings, on='movieId', how='outer')
    (df.groupby('title')['rating'].count().sort_values(ascending=False).head())
    ratings = pd.DataFrame(df.groupby('title')['rating'].mean())
    moviemat = df.pivot_table(index='userId', columns='title', values='rating')
    ratings = pd.DataFrame(df.groupby('title')['rating'].mean())
    ratings['num of ratings'] = pd.DataFrame(df.groupby('title')['rating'].count())
    # print(ratings.sort_values('num of ratings',ascending=False).head(10))
    movie_name = request.POST.get('search')
    user_ratings1 = moviemat[movie_name]
    user_ratings1.head()
    similar_to_starwars = moviemat.corrwith(user_ratings1)
    corr_ur = pd.DataFrame(similar_to_starwars, columns=['Correlation'])
    corr_ur.dropna(inplace=True)
    corr_ur.sort_values('Correlation', ascending=False).head(10)
    corr_ur = corr_ur.join(ratings['num of ratings'])
    variable = corr_ur[corr_ur['num of ratings'] > 100].sort_values('Correlation', ascending=False).head()
    results = pd.DataFrame(
        columns=['title',
                 'rating']
    )
    x = variable.to_dict(orient='dict')
    df = pd.DataFrame.from_dict(x, orient='columns')
    df.transpose()
    results = pd.concat([results, df], sort=False)
    a=[]
    a=results['title']
    b=[]
    b=results['rating']
   # variable.dropna(inplace=True)
    #variable_dict = variable.to_dict('series')
    #vv = variable_dict
    #=[]
    ##print(vv)
   # print('123',vv)
   #context = {
     #   'contexts':vv,

    return render(request, 'main/mainpage.html',{'a':a,'b':b})

main/templates/main/adv.html
{%load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Adventure</title>
	<link rel="stylesheet" type="text/css" href="{%static 'main/adv.css'%}">
</head>
<body>
	<h1>Adventures Movies</h1>
		<table>
			<tr>
				<th>List</th>
			</tr>
			<tr>
				<td colspan="4">Click on movie</td>
			</tr>
			<tr>
				<td><a href="adv.html">
					<img src="movie39.jpg">
					Cutthroat Island (1995)
				</a></td>
				<td><a href="adv.html">
					<img src="movie1.jpg">
					Toy Story (1995)
				</a></td>
				<td><a href="adv.html">
					<img src="movie4.jpg">
					Tom and Huck (1995)
				</a></td>
				<td><a href="adv.html">
					<img src="movie2.jpg">
					Jumanji (1995)
				</a></td>
				<td><a href="adv.html">
					<img src="movie37.jpg">
					GoldenEye (1995)
				</a></td>
				<td><a href="adv.html">
					<img src="movie38.jpg">
					Balto (1995)
				</a></td>
				
			</tr>
			<tr>
				<td><a href="frend4.html">
					<img src="movie40.jpg">
					Mortal Kombat (1995)
				</a></td>
				<td><a href="frend4.html">
					<img src="movie41.jpg">
					Lamerica (1994)
				</a></td>
				<td><a href="frend4.html">
					<img src="movie42.jpg">
					Indian in the Cupboard, The (1995)
				</a></td>
				<td><a href="frend4.html">
					<img src="movie43.jpg">
					White Squall (1996)
				</a></td>
				<td><a href="frend4.html">
					<img src="movie44.jpg">
					Broken Arrow (1996)
				</a></td>
				<td><a href="frend4.html">
					<img src="movie45.jpg">
					Bottle Rocket (1996)
				</a></td>
				
			</tr>
		</table>


</body>
</html>

main/templates/main/anime.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
	<title>Animation</title>
	<link rel="stylesheet" type="text/css" href="{%static 'main/anime.css'%}">
</head>
<body>
	<h1>Animation Movies</h1>
		<table>
			<tr>
				<th>List</th>
			</tr>
			<tr>
				<td colspan="4">Click on movie</td>
			</tr>
			<tr>
				<td><a href="frend4.html">
					<img src="movie54.jpg">
					Pocahontas (1995)
				</a></td>
				<td><a href="frend4.html">
					<img src="movie55.jpg">
					Goofy Movie, A (1995)
				</a></td>
				<td><a href="frend4.html">
					<img src="movie59.jpg">
					Swan Princess, The (1994)
				</a></td>
				<td><a href="frend4.html">
					<img src="movie56.jpg">
					Lion King, The (1994)
				</a></td>
				<td><a href="frend4.html">
					<img src="movie57.jpg">
					Nightmare Before Christmas, The (1993)
				</a></td>
				<td><a href="frend4.html">
					<img src="movie58.jpg">
					Pagemaster, The (1994)
				</a></td>

			</tr>
			<tr>
				<td><a href="frend4.html">
					<img src="movie60.jpg">
					Aladdin (1992)
				</a></td>
				<td><a href="frend4.html">
					<img src="movie61.jpg">
					Snow White and the Seven Dwarfs (1937)
				</a></td>
				<td><a href="frend4.html">
					<img src="movie62.jpg">
					Beauty and the Beast (1991)
				</a></td>
				<td><a href="frend4.html">
					<img src="movie63.jpg">
					Pinocchio (1940)
				</a></td>
				<td><a href="frend4.html">
					<img src="movie64jpg.jpg">
					Heavy Metal (1981)
				</a></td>
				<td><a href="frend4.html">
					<img src="movie65.jpg">
					Aristocats, The (1970)
				</a></td>

			</tr>
		</table>


</body>
</html>

main/templates/main/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<style>
body {
    background-image:url("https://www.hdwallpapers.in/download/the_peanuts_movie-wide.jpg");
}
</style>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
{# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">MRS</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'main:register' %}">Register</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'main:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

main/templates/main/index.html
{% extends "main/base.html" %}
<html>
<head>
	<title>Welcome!!!</title>
<style>
*{
	margin:0;
	padding: 0;
	font-family: Times;
}
header{
	background:linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)),url('http://www.solidbackgrounds.com/2560x1440-white-solid-color-background.html');
	height: 100vh;
	background-size: cover;
	background-position: center;
}
h2{
	color:#fff;
	}
ul{
	float: right;
	list-style-type: none;
	margin-top: 25px;
	margin-right: 15px;

}
ul li{
	display: inline-block;
}
ul li a{
	text-decoration: none;
	color: #fff;
	padding: 5px 20px;
	border: 1px solid transparent;
	transition: 0.6s ease;
}
ul li a:hover{
	background-color: #fff;
	color: #000;
}
.main{
	max-width: 1200px;
	margin: auto;
}
ul li.active a{
	background-color: #fff;
	color: #000;
}
.title{
	position: absolute;
	left: 50%;
	top: 50%;
	transform: translate(-50%,-50%);
	border-radius: 20px;
	margin: auto;
	background: rgba(0,0,0,0.8);
	box-sizing: border-box;
	padding: 40px;
	color: #fff;

}
.title h1{
	color: #fff;
	font-size: 60px;
	font-family: Times;
}
.fname{
	position: absolute;
	left: 88%;
	transform: translate(-50%,-50%);
	margin-top: 590px;
}
.fname h2{
	color: #fff;
	font-size: 26px;
	font-family: Times;
}
.made{
	position: absolute;
	left: 80%;
	transform: translate(-50%,-50%);
	margin-top: 500px;

}
.made h2{
	color: #fff;
	font-size: 30px;
	font-family: Times;
}
/* Popup container */
.popup {
  position: relative;
  display: inline-block;
  cursor: pointer;
}

/* The actual popup (appears on top) */
.popup .popuptext {
  visibility: hidden;
  width: 160px;
  background-color: #555;
  color: #fff;
  text-align: center;
  border-radius: 6px;
  padding: 8px 0;
  position: absolute;
  z-index: 1;
  bottom: 125%;
  left: 50%;
  margin-left: -80px;
}

/* Popup arrow */
.popup .popuptext::after {
  content: "";
  position: absolute;
  top: 100%;
  left: 50%;
  margin-left: -5px;
  border-width: 5px;
  border-style: solid;
  border-color: #555 transparent transparent transparent;
}

/* Toggle this class when clicking on the popup container (hide and show the popup) */
.popup .show {
  visibility: visible;
  -webkit-animation: fadeIn 1s;
  animation: fadeIn 1s
}

/* Add animation (fade in the popup) */
@-webkit-keyframes fadeIn {
  from {opacity: 0;}
  to {opacity: 1;}
}

@keyframes fadeIn {
  from {opacity: 0;}
  to {opacity:1 ;}
}
</style>
</head>
<body>

        {% block body_block %}
		<div class="title">
			<h1>Movies Recommendation System</h1>
		</div>
		<div class="fname">
			<h2>Yashita</h2>
			<h2>Ujjwal</h2>
			<h2>Radhika</h2>
		</div>
		<div class="made">
			<h2></h2>
		</div>
        {% endblock %}

</body>
</html>

main/templates/main/login.html
{% extends 'main/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'main:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

main/templates/main/mainpage.html
<style type="text/css">
	@import url(https://fonts.googleapis.com/css?family=Exo+2:200i);

:root {
  /* Base font size */
  font-size: 4px;

  /* Set neon color */
  --neon-text-color: #f40;
  --neon-border-color: #08f;
}

body {
  font-family: 'Exo 2', sans-serif;
  display: flex;
  justify-content: center;
  align-items: center;
  background: url('movie31.jpg');
  min-height: 30vh;
}

h1 {
  font-size: 13rem;
  font-weight: 200;
  font-style: italic;
  color: #fff;
  padding: 4rem 6rem 5.5rem;
  border: 0.4rem solid #fff;
  border-radius: 2rem;
  text-transform: uppercase;
  animation: flicker 1.5s infinite alternate;
}

h1::-moz-selection {
  background-color: var(--neon-border-color);
  color: var(--neon-text-color);
}

h1::selection {
  background-color: var(--neon-border-color);
  color: var(--neon-text-color);
}

h1:focus {
  outline: none;
}

/* Animate neon flicker */
@keyframes flicker {

    0%, 19%, 21%, 23%, 25%, 54%, 56%, 100% {

        text-shadow:
            -0.2rem -0.2rem 1rem #fff,
            0.2rem 0.2rem 1rem #fff,
            0 0 2rem var(--neon-text-color),
            0 0 4rem var(--neon-text-color),
            0 0 6rem var(--neon-text-color),
            0 0 8rem var(--neon-text-color),
            0 0 10rem var(--neon-text-color);

        box-shadow:
            0 0 .5rem #fff,
            inset 0 0 .5rem #fff,
            0 0 2rem var(--neon-border-color),
            inset 0 0 2rem var(--neon-border-color),
            0 0 4rem var(--neon-border-color),
            inset 0 0 4rem var(--neon-border-color);
    }

    20%, 24%, 55% {
        text-shadow: none;
        box-shadow: none;
    }
}
.main{
  max-width: 50px;
  margin: auto;
}
body{
  text-align: center;
  font-size: 30px;
}
h1{
  margin-top: -190px;
}
input[type=text]{
	width: 200%;
	height: 150px;
	box-sizing: border-box;
	padding: 1px 1px;
	background: #fff;
	outline: none;
	border:none;
	border-bottom: 1px ridge #fff;
	border-radius: 5px;
	margin: 5px;
	font-weight: bold;
	color: #92a8d1;
}

ul{
  float: right;
  list-style-type: none;
  margin-top: -1600px;
  margin-right: -20px;

}
ul li{
  display: inline-block;
}
ul li a{
  text-decoration: none;
  color: #fff;
  padding: 5px 20px;
  border: 1px solid transparent;
  transition: 0.6s ease;
}
ul li a:hover{
  background-color: #fff;
  color: #000;
}
h2{
  margin-top: 400px;
  color: #fff;
}
.a{
	text-align:center;
	color:#111;
}


</style>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Final Page</title>
</head>
<style>
body {
    background-image:url("http://www.solidbackgrounds.com/2560x1440-white-solid-color-background.html");
}
input[type=text]{
	width: 200%;
	height: 100px;
	box-sizing: border-box;
	padding: 1px 1px;
	background: #fff;
	outline: none;
	top:20%;
	border:none;
	border-bottom: 1px ridge #fff;
	border-radius: 5px;
	margin: 5px;
	font-weight: bold;
	color: #92a8d1;
}

</style>
<body>
	<h1 contenteditable spellcheck="false">Movie Recommended</h1>
	<div class="a">
	{{a}}
	{{b}}
	</div>
</body>
     {% for i in contexts %}
	     {{ i }}
	 {% endfor %}
		</form>
		<div class="main">
			<ul>
				<li><a href="frend2.html">  Log out </a></li>
			</ul>
		</div>
</body>
</html>

main/templates/main/registeration.html
{% extends "main/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}
    </div>
  </div>
{% endblock %}

main/templates/main/successpage.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<!link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    @import url(https://fonts.googleapis.com/css?family=Exo+2:200i);

:root {
  /* Base font size */
  font-size: 4px;

  /* Set neon color */
  --neon-text-color: #f40;
  --neon-border-color: #08f;
}

body {
  font-family: 'Exo 2', sans-serif;
  display: flex;
  justify-content: center;
  align-items: center;
  background-image:url("https://www.hdwallpapers.in/download/the_peanuts_movie-wide.jpg");
  min-height: 30vh;
}

h1 {
  font-size: 13rem;
  font-weight: 200;
  font-style: italic;
  color: #fff;
  padding: 4rem 6rem 5.5rem;
  border: 0.4rem solid #fff;
  border-radius: 2rem;
  text-transform: uppercase;
  animation: flicker 1.5s infinite alternate;
}

h1::-moz-selection {
  background-color: var(--neon-border-color);
  color: var(--neon-text-color);
}

h1::selection {
  background-color: var(--neon-border-color);
  color: var(--neon-text-color);
}

h1:focus {
  outline: none;
}

/* Animate neon flicker */
@keyframes flicker {

    0%, 19%, 21%, 23%, 25%, 54%, 56%, 100% {

        text-shadow:
            -0.2rem -0.2rem 1rem #fff,
            0.2rem 0.2rem 1rem #fff,
            0 0 2rem var(--neon-text-color),
            0 0 4rem var(--neon-text-color),
            0 0 6rem var(--neon-text-color),
            0 0 8rem var(--neon-text-color),
            0 0 10rem var(--neon-text-color);

        box-shadow:
            0 0 .5rem #fff,
            inset 0 0 .5rem #fff,
            0 0 2rem var(--neon-border-color),
            inset 0 0 2rem var(--neon-border-color),
            0 0 4rem var(--neon-border-color),
            inset 0 0 4rem var(--neon-border-color);
    }

    20%, 24%, 55% {
        text-shadow: none;
        box-shadow: none;
    }
}
.main{
  max-width: 50px;
  margin: auto;
}
body{
  text-align: center;
  font-size: 30px;
}
h1{
  margin-top: 100px;
}


ul{
  float: right;
  list-style-type: none;
  margin-top: -1600px;
  margin-right: -20px;

}
ul li{
  display: inline-block;
}
ul li a{
  text-decoration: none;
  color: #fff;
  padding: 5px 20px;
  border: 1px solid transparent;
  transition: 0.6s ease;
}
ul li a:hover{
  background-color: #fff;
  color: #000;
}
h2{
  margin-top: 400px;
  color: #fff;
}


</style>
</head>
<body>

<h1>Enter a Movie</h1>


  <form method="POST" action="mainpage/">
	{% csrf_token %}
    <input type="text" style="margin-top:300px;" placeholder="Search.." name="search">
    <button type="submit"><i class="fa fa-search"></i></button>
  </form>



</body>
</html>